### ISSUE TITLE
اقا مهراب سلام . 

### ISSUE THREAD

**Issue by massooti** [mehrab-wj/SimplePHPBot#2]
اقا مهراب سلام . من توی استفاده از این ربات شما مشکل دارم کمکمون میکنی؟
من توکن ربات رو ست میکنم همه چی اوکی ردیف اما بعدش توی ربات تلگرام هیچ اتفاقی نمیوفته یعنی هرچی تایپ میکنم دستور میزنم هیچ اتفاقی نمیوفته .
ممکنه یه راهنمایی بکنی؟

**Comment by mehrab-wj** [comment]
سلام دوست عزیز
آیا وب هوک هم ست کردید ؟

**Comment by massooti** [comment]
والا وب هوک رو هم ست میکنم اما بعد از اینکه کد هارو هم به از تغیرات ذخیره میکنم  اینور توی ربات تلگرام هیچ اتفاقی نمیوفته
میخوای من کدی که تغییر دادم رو بفرستم شما یه بررسی بکنی؟

**Comment by mehrab-wj** [comment]
دوست عزیز متاسفانه وقت ندارم کد هاتون رو برسی کنم
ارور لاگ رو ببینید تا متوجه بشید کد هاتون مشکل داره یا خیر
همچنین مطمعن بشید که هاستتون SSL داره
